const { test, expect } = require('@playwright/test');

// Helper function to log in securely
async function login(page, username, password) {
  await page.goto('/login');
  await page.fill('#username', username);
  await page.fill('#password', password);
  await page.click('button[type="submit"]');
  // Wait until logged in (redirected to dashboard/web context) and not the login page
  await page.waitForURL(url => url.pathname.includes('/web/') && !url.pathname.includes('/login'));
}

test.describe.serial('Real User Journey E2E Specs', () => {

  test.beforeAll(async ({ browser }) => {
    // Reset database state to guarantee baseline roster
    const page = await browser.newPage();
    await page.goto('/test/reset');
    await page.close();
  });

  test('TEST 1 — Admin Journey', async ({ page }) => {
    // Login as admin@greenwood.com, assert redirect to admin dashboard
    await login(page, 'admin@greenwood.com', 'PilotLaunchSecure2026!');
    await expect(page.url()).toContain('/web/admin/dashboard');

    // Add a new student
    await page.goto('/web/admin/management');
    await page.click('button:has-text("Register New Student")');
    await expect(page.locator('#registerStudentModal')).toBeVisible();
    await page.fill('#firstName', 'Test');
    await page.fill('#lastName', 'Student Playwright');
    await page.fill('#rollNumber', '6A-99');
    await page.selectOption('#schoolClassId', { label: 'Grade 6 - A' });
    await page.click('button:has-text("Register Student")');
    await page.waitForURL(url => url.pathname.includes('/web/admin/management'));

    // Search for a student by name using rosterSearchInput
    await page.goto('/web/admin/dashboard?classId=11111111-2222-3333-4444-555555555551');
    await page.fill('#rosterSearchInput', 'Test Student Playwright');
    
    // Assert row is visible
    const studentRow = page.locator('tr:has-text("Test Student Playwright")').first();
    await expect(studentRow).toBeVisible();

    // Delete that student, assert no 500 error and row disappears
    const deleteTrigger = studentRow.locator('button:has-text("🗑️")');
    await deleteTrigger.click();
    await expect(page.locator('#deleteModal')).toBeVisible();
    await page.click('#deleteForm button[type="submit"]');
    await page.waitForURL(url => url.pathname.includes('/web/admin/management'));
    await expect(page.locator('body')).not.toContainText('Whitelabel Error Page');
    
    // Open fee management page, assert KPI cards are visible
    await page.goto('/web/admin/fees');
    await expect(page.locator('text=Total Revenue Target')).toBeVisible();
    await expect(page.locator('text=Total Collected Invoices')).toBeVisible();

    // Post a new announcement, assert it appears in the list
    await page.goto('/web/admin');
    const uniqueTitle = 'Playwright Announcement ' + Math.random();
    await page.fill('#title', uniqueTitle);
    await page.selectOption('#targetGrade', 'Grade 6');
    await page.fill('#content', 'This is a test announcement generated by Playwright.');
    await page.click('button:has-text("Broadcast Notice")');
    await page.waitForURL(url => url.pathname.includes('/web/admin/dashboard'));
    
    await page.context().clearCookies();
  });

  test('TEST 2 — Teacher Journey', async ({ page }) => {
    // Login as teacher@greenwood.com, assert redirect to dashboard
    await login(page, 'teacher@greenwood.com', 'PilotLaunchSecure2026!');
    await expect(page.url()).toContain('/web/teacher/dashboard'); // Teacher redirects to teacher dashboard

    // Open attendance page
    await page.goto('/web/teacher/attendance');
    
    // Select first classroom from dropdown
    await Promise.all([
      page.waitForURL(url => url.pathname.includes('/web/teacher/attendance') && url.searchParams.has('classId')),
      page.selectOption('select', { index: 1 })
    ]);
    
    // Mark first student Present, second student Absent
    const firstPresentBtn = page.locator('button[id^="btn_present_"]').nth(0);
    const secondAbsentBtn = page.locator('button[id^="btn_absent_"]').nth(1);
    await firstPresentBtn.click();
    await secondAbsentBtn.click();
    
    // Click save/dispatch button, assert warning modal appears
    await page.click('button:has-text("Save Daily Attendance Log")');
    const confirmModal = page.locator('#confirmModal');
    await expect(confirmModal).toBeVisible();
    
    // Confirm submission, assert no error
    await page.click('button:has-text("Save & Dispatch")');
    const successToast = page.locator('#toast');
    await expect(successToast).toContainText('Attendance Ledger Saved Successfully.');
    await expect(page.locator('body')).not.toContainText('Whitelabel Error Page');
    
    await page.context().clearCookies();
  });

  test('TEST 3 — Parent Journey (isolation test)', async ({ page }) => {
    // Login as ramesh@gmail.com, assert redirect to parent dashboard
    await login(page, 'ramesh@gmail.com', 'PilotLaunchSecure2026!');
    await expect(page.url()).toContain('/web/parent/portal');
    
    // Assert linked child name is visible on dashboard (Arjun Sharma)
    await expect(page.locator('body')).toContainText('Arjun Sharma');
    
    // Handle dialog alerts for parent task assignment
    page.on('dialog', async dialog => {
      await dialog.accept();
    });

    // Assign a quest with title Home Quest Playwright Test and xp bounty 50
    await page.fill('#taskDescription', 'Home Quest Playwright Test');
    await page.fill('#xpBounty', '50');
    
    await Promise.all([
      page.waitForNavigation(),
      page.click('button:has-text("Assign Task")')
    ]);
    
    await page.context().clearCookies();
    
    // Login as ramesh@gmail.com, assert their dashboard loads
    await login(page, 'ramesh@gmail.com', 'PilotLaunchSecure2026!');
    await expect(page.url()).toContain('/web/parent/portal');
    
    // Assert ramesh@gmail.com's dashboard does NOT contain the student created by Admin
    await expect(page.locator('body')).not.toContainText('Test Student Playwright');
    
    // Logout cleanly
    await page.context().clearCookies();
  });

  test('TEST 4 — Student Journey', async ({ page }) => {
    // Login as first seeded student
    await login(page, 'arjun@gmail.com', 'PilotLaunchSecure2026!');
    
    // Assert redirect to student portal
    await expect(page.url()).toContain('/web/student/portal'); // Wait, student portal is /web/student/portal? The previous scripts used /web/student/portal?tab=dashboard. I'll check. Let's navigate to /web/student/portal?tab=dashboard to be safe.
    await page.goto('/web/student/portal');
    // Assert XP progress bar is visible
    const xpSpan = page.locator('span:near(span:has-text("Total XP"))').first();
    await expect(xpSpan).toBeVisible();
    
    // Assert streak counter is visible
    await expect(page.locator('text=Active Streak').first()).toBeVisible();
    
    await page.locator('[data-tab="challenges"]').first().click();
    // Wait for challenges tab JS to load (scholastic tasks fetched async)
    await page.waitForFunction(() => {
      const c = document.getElementById('scholastic-tasks-container');
      return c && !c.innerHTML.includes('Loading tasks...');
    }, { timeout: 30000 });
    
    // Open Home Quest Board, assert the quest assigned by ramesh@gmail.com is visible
    await expect(page.locator('h4:has-text("Home Quest Playwright Test")').first()).toBeVisible();
    
    // Click Mark Done on that quest, assert confirmation
    const claimQuestLink = page.locator('a[href*="/web/student/quest/"][href$="/claim"]').first();
    await claimQuestLink.click();
    await expect(page.locator('#toast')).toContainText('Home quest marked as completed!');
    
    // Open Milestone Submission form (on dashboard), fill dummy data, submit
    await page.goto('/web/student/portal');
    await page.locator('[data-tab="challenges"]').first().click();
    await page.waitForFunction(() => {
      const c = document.getElementById('scholastic-tasks-container');
      return c && !c.innerHTML.includes('Loading tasks...');
    }, { timeout: 30000 });
    await page.selectOption('#skillName', { index: 1 });
    await page.fill('#proofOfWorkNotes', 'Testing dummy proof notes for milestone');
    await page.click('button:has-text("Submit Milestone Evidence")');
    await expect(page.locator('#toast')).toContainText('Milestone submitted successfully!');
    
    // Open Rewards Ledger, assert both School and Parent reward tabs load
    await page.goto('/web/student/portal');
    await page.locator('[data-tab="rewards"]').first().click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('h3:has-text("Rewards Ledger")')).toBeVisible();
    await expect(page.locator('h3:has-text("Parent-Defined Custom Rewards")')).toBeVisible();
    
    // Open Submission History, assert at least one entry is visible
    await page.goto('/web/student/portal');
    await page.locator('[data-tab="profile"]').first().click();
    await page.waitForLoadState('domcontentloaded');
    await expect(page.locator('h3:has-text("Submission History Log")')).toBeVisible();
    
    // Logout cleanly
    await page.context().clearCookies();
  });

});
